[theme]
name = 'Maple'
comment = 'The Maple Cursor'
website = 'https://github.com/Liam-Weitzel/maplestory-cursor'

[config]
bitmaps_dir = 'bitmaps/Maple'
out_dir = 'themes'
platforms = ['x11', 'windows']
x11_sizes = [22, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
win_size = 32

[cursors]

[cursors.fallback_settings]
x_hotspot = 16
y_hotspot = 16
x11_delay = 400
win_delay = 1

# all-scroll
[cursors.all-scroll]
png = 'all-scroll-*.png'
x11_delay = 120
win_delay = 1
x11_name = 'all-scroll'
x11_symlinks = ['fleur', 'size_all']

# bd-double-arrow
[cursors.bd-double-arrow]
png = 'bd-double-arrow-*.png'
x11_delay = 120
x11_name = 'bd_double_arrow'
win_name = 'Diagonal_1'
x11_symlinks = [
  'c7088f0f3e6c8088236ef8e1e3e70000',
  'nw-resize',
  'nwse-resize',
  'size_fdiag',
  'se-resize',
  'bottom_left_corner',
  'top_left_corner'
]

# fd-double-arrow
[cursors.fd-double-arrow]
png = 'fd-double-arrow-*.png'
x11_delay = 120
x11_name = 'fd_double_arrow'
win_name = 'Diagonal_2'
x11_symlinks = [
  'fcf1c3c7cd4491d801f1e1c78f100000',
  'ne-resize',
  'nesw-resize',
  'sw-resize',
  'size_bdiag',
  'bottom_right_corner',
  'top_right_corner'
]

# point.png
[cursors.point]
png = 'point.png'
x11_name = 'left_ptr'
win_name = 'Default'
x11_symlinks = [
  'arrow', 'default', 'top_left_arrow',
  'center_ptr',
  'cross', 'cross_reverse', 'diamond_cross', 'tcross', 'crosshair',
  'dotbox', 'dot_box_mask', 'draped_box', 'icon', 'target',
  'pencil', 'draft',
  'plus', 'cell',
  'vertical-text', 'ibeam', 'text'
]

# point-click-right-page
[cursors.point-click-right]
png = 'point-click-right-page-*.png'
x11_name = 'hand2'
win_name = 'Link'
x11_symlinks = [
  '9d800788f1b08800ae810202380a0822',
  'e29285e634086352946a0e7090d73106',
  'pointer',
  'pointing_hand',
  'right_ptr',
  'draft_large',
  'draft_small'
]

# point-click-page
[cursors.point-click]
png = 'point-click-page-*.png'
x11_name = 'copy'
x11_symlinks = [
  '1081e37283d90000800003c07f3ef6bf',
  '6407b0e94181790501fd1e167b474872',
  'b66166c04f8c3109214a4fbd64a50fc8',
  'dnd-copy',
  'context-menu'
]

# point-horizontal-green-page
[cursors.horizontal-green]
png = 'point-horizontal-green-page-*.png'
x11_delay = 120
x11_name = 'col-resize'
x11_symlinks = [
  'split_h',
  'left_side',
  'right_side',
  'sb_h_double_arrow',
  '028006030e0e7ebffc7f7070c0600140',
  '14fef782d02440884392942c1120523',
  'e-resize',
  'ew-resize',
  'h_double_arrow',
  'size-hor',
  'size_hor',
  'w-resize',
  'sb_left_arrow',
  'left-arrow',
  'sb_right_arrow',
  'right-arrow'
]

# bottom-side
[cursors.bottom-side]
png = 'bottom-side-*.png'
x11_delay = 120
x11_name = 'bottom_side'
x11_symlinks = [
  'row-resize',
  'split_v',
  'sb_down_arrow',
  'down-arrow',
  'sb_up_arrow',
  'up-arrow',
  'sb_v_double_arrow',
  '00008160000006810000408080010102',
  '2870a09082c103050810ffdffffe0204',
  'double_arrow',
  'n-resize',
  'ns-resize',
  'size-ver',
  'size_ver',
  's-resize',
  'v_double_arrow',
  'top_side'
]

# point_lock_page
[cursors.lock-page]
png = 'point_lock_page_*.png'
x11_name = 'crossed_circle'
x11_symlinks = [
  'forbidden',
  'not-allowed',
  'dnd_no_drop',
  '03b6e0fcb3499374a867c041f52298f0',
  'circle',
  'dnd-no-drop',
  'no-drop',
  'pirate'
]

# magnifying-glass-click-page
[cursors.magnifying-glass]
png = 'magnifying-glass-click-page-*.png'
x11_name = 'color-picker'
x11_symlinks = [
  'zoom-in',
  'zoom-out'
]

# grab-page
[cursors.grab]
png = 'grab-page-*.png'
x11_delay = 120
x11_name = 'hand1'
win_name = 'Move'
x11_symlinks = ['grab', 'openhand']

# grab-page-03
[cursors.grabbing]
png = 'grab-page-03.png'
x11_name = 'move'
x11_symlinks = [
  '4498f0e0c1937ffe01fd06f973665830',
  '9081237383d90e509aa00f00170e968f',
  'fcf21c00b30f7e3f83fe0dfd12e71cff',
  'grabbing',
  'pointer_move',
  'dnd-move',
  'closedhand',
  'dnd-none'
]

# meso-coin-copper-page
[cursors.wait]
png = 'meso-coin-copper-page-*.png'
x11_delay = 120
x11_name = 'wait'
win_name = 'Busy'
x11_symlinks = [
  'watch',
  'left_ptr_watch',
  '00000000000000020006000e7e9ffc3f',
  '08e8e1c95fe2fc01f976f1e063a24ccd',
  '3ecb610c1bf2410f44200f48c40d3599',
  'progress'
]

# link
[cursors.link]
png = 'link-*.png'
x11_name = 'link'
x11_symlinks = [
  '3085a0e285430894940527032f8b26df',
  '640fb0e74195791501fd1ed57b41487f',
  'a2a266d0498c3104214a47bd64ab0fc8',
  'alias',
  'dnd-link'
]

# question
[cursors.question]
png = 'question.png'
x11_name = 'question_arrow'
win_name = 'Help'
x11_symlinks = [
  '5c6cd98b3f3ebcb1f9c7f1c204630408',
  'd9ce0ab605698f320427677b458ad60b',
  'help',
  'left_ptr_help',
  'whats_this',
  'dnd-ask'
]
